// Shared institution seed data — used by both the seed script and the in-app seed route.
const institutions = [

  // ── Federal Agencies ──────────────────────────────────────────────
  { name: 'National Archives and Records Administration (NARA)', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.archives.gov', notes: 'Primary federal archive; major contractor for digitization, preservation, and records management.' },
  { name: 'Library of Congress', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.loc.gov', notes: 'Largest library in the world; contracts for preservation, digitization, and special collections work.' },
  { name: 'Smithsonian Institution', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.si.edu', notes: 'World\'s largest museum and research complex; 19 museums and 21 libraries.' },
  { name: 'National Park Service', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.nps.gov', notes: 'Historic preservation, cultural resources management, Section 106 compliance contracts.' },
  { name: 'National Endowment for the Humanities (NEH)', institution_type: 'Federal Funder', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.neh.gov', notes: 'Key grant funder for preservation, digitization, and humanities projects.' },
  { name: 'National Endowment for the Arts (NEA)', institution_type: 'Federal Funder', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.arts.gov', notes: 'Federal grant funder for arts and cultural organizations.' },
  { name: 'Institute of Museum and Library Services (IMLS)', institution_type: 'Federal Funder', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.imls.gov', notes: 'Primary federal funder for museums and libraries; LSTA and Museums for America grants.' },
  { name: 'Advisory Council on Historic Preservation (ACHP)', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.achp.gov', notes: 'Section 106 regulatory authority; consultation and compliance work.' },
  { name: 'Department of the Interior', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.doi.gov', notes: 'Parent agency for NPS, BLM, BIA — broad historic preservation and cultural resource contracts.' },
  { name: 'Bureau of Land Management (BLM)', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.blm.gov', notes: 'Cultural resources management on public lands; Section 106 compliance.' },
  { name: 'US Army Corps of Engineers', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.usace.army.mil', notes: 'Cultural resources and historic preservation requirements on infrastructure projects.' },
  { name: 'General Services Administration (GSA)', institution_type: 'Federal Agency', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.gsa.gov', notes: 'Manages historic federal buildings; contracts for preservation and documentation work.' },
  { name: 'African American Cultural Heritage Action Fund', institution_type: 'Federal Program', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://savingplaces.org/african-american-cultural-heritage', notes: 'National Trust program specifically funding African American historic sites.' },

  // ── Smithsonian Museums ───────────────────────────────────────────
  { name: 'National Museum of African American History and Culture (NMAAHC)', institution_type: 'Museum', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://nmaahc.si.edu', notes: 'Smithsonian. Contracts for collections management, research, and educational programming.' },
  { name: 'National Museum of American History', institution_type: 'Museum', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://americanhistory.si.edu', notes: 'Smithsonian. Collections preservation and digitization opportunities.' },
  { name: 'Anacostia Community Museum', institution_type: 'Museum', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://anacostia.si.edu', notes: 'Smithsonian community museum focused on African American urban history.' },
  { name: 'National Portrait Gallery', institution_type: 'Museum', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://npg.si.edu', notes: 'Smithsonian. Collections preservation, research, and documentation work.' },

  // ── African American History Museums ─────────────────────────────
  { name: 'Charles H. Wright Museum of African American History', institution_type: 'Museum', relationship_status: 'Target', city: 'Detroit', state: 'MI', website: 'https://www.thewright.org', notes: 'World\'s largest institution dedicated to African American history and culture.' },
  { name: 'DuSable Black History Museum and Education Center', institution_type: 'Museum', relationship_status: 'Target', city: 'Chicago', state: 'IL', website: 'https://www.dusablemuseum.org', notes: 'Chicago\'s premier Black history institution; collections preservation opportunities.' },
  { name: 'African American Museum in Philadelphia', institution_type: 'Museum', relationship_status: 'Target', city: 'Philadelphia', state: 'PA', website: 'https://www.aampmuseum.org', notes: 'First museum built by a major US city to house and interpret African American culture.' },
  { name: 'National Civil Rights Museum', institution_type: 'Museum', relationship_status: 'Target', city: 'Memphis', state: 'TN', website: 'https://www.civilrightsmuseum.org', notes: 'Located at the Lorraine Motel. Preservation and archival work opportunities.' },
  { name: 'Birmingham Civil Rights Institute', institution_type: 'Museum', relationship_status: 'Target', city: 'Birmingham', state: 'AL', website: 'https://www.bcri.org', notes: 'Documents the Civil Rights Movement; archive and digitization opportunities.' },
  { name: 'National Museum of African American Music', institution_type: 'Museum', relationship_status: 'Target', city: 'Nashville', state: 'TN', website: 'https://nmaam.org', notes: 'Opened 2021; collections development and digitization opportunities.' },
  { name: 'Reginald F. Lewis Museum of Maryland African American History', institution_type: 'Museum', relationship_status: 'Target', city: 'Baltimore', state: 'MD', website: 'https://lewismuseum.org', notes: 'Largest African American museum on the East Coast outside DC.' },
  { name: 'Harvey B. Gantt Center for African-American Arts + Culture', institution_type: 'Museum', relationship_status: 'Target', city: 'Charlotte', state: 'NC', website: 'https://ganttcenter.org', notes: 'Arts and cultural heritage preservation opportunities.' },

  // ── Historical Societies & Archives ──────────────────────────────
  { name: 'Association for the Study of African American Life and History (ASALH)', institution_type: 'Historical Society', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://asalh.org', notes: 'Founded by Carter G. Woodson. Archive and preservation partnership opportunities.' },
  { name: 'National Trust for Historic Preservation', institution_type: 'Nonprofit / Advocacy', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://savingplaces.org', notes: 'Key national partner for historic preservation; issues grants and holds preservation easements.' },
  { name: 'Society of American Archivists (SAA)', institution_type: 'Professional Association', relationship_status: 'Target', city: 'Chicago', state: 'IL', website: 'https://www2.archivists.org', notes: 'National professional association; conference, publications, and partnership opportunities.' },
  { name: 'American Alliance of Museums (AAM)', institution_type: 'Professional Association', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.aam-us.org', notes: 'National museum association; accreditation and standards; partnership opportunities.' },
  { name: 'Preservation Action', institution_type: 'Nonprofit / Advocacy', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.preservationaction.org', notes: 'Federal historic preservation advocacy; good for tracking policy and funding.' },
  { name: 'Maryland Historical Society', institution_type: 'Historical Society', relationship_status: 'Target', city: 'Baltimore', state: 'MD', website: 'https://mdhs.org', notes: 'Oldest cultural institution in Maryland; large archive and library.' },
  { name: 'Virginia Museum of History and Culture', institution_type: 'Historical Society', relationship_status: 'Target', city: 'Richmond', state: 'VA', website: 'https://virginiahistory.org', notes: 'Collections preservation and digitization opportunities.' },
  { name: 'Georgia Historical Society', institution_type: 'Historical Society', relationship_status: 'Target', city: 'Savannah', state: 'GA', website: 'https://georgiahistory.com', notes: 'Statewide historical society; archival and preservation opportunities.' },
  { name: 'Texas State Library and Archives Commission', institution_type: 'State Agency', relationship_status: 'Target', city: 'Austin', state: 'TX', website: 'https://www.tsl.texas.gov', notes: 'State archives and records management; digitization and preservation contracts.' },
  { name: 'California Historical Society', institution_type: 'Historical Society', relationship_status: 'Target', city: 'San Francisco', state: 'CA', website: 'https://californiahistoricalsociety.org', notes: 'Statewide historical society with significant collections.' },
  { name: 'National Coalition for History', institution_type: 'Nonprofit / Advocacy', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://historycoalition.org', notes: 'Federal policy advocacy for history and archives funding.' },

  // ── HBCUs ─────────────────────────────────────────────────────────
  { name: 'Howard University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.howard.edu', notes: 'Moorland-Spingarn Research Center holds one of the largest African American archives in the world.' },
  { name: 'Fisk University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Nashville', state: 'TN', website: 'https://www.fisk.edu', notes: 'Houses the Fisk Jubilee Singers archive and significant African American art collection.' },
  { name: 'Spelman College', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Atlanta', state: 'GA', website: 'https://www.spelman.edu', notes: 'Archives and special collections; women\'s history and African American studies.' },
  { name: 'Hampton University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Hampton', state: 'VA', website: 'https://www.hamptonu.edu', notes: 'Hampton University Museum holds significant Native American and African American collections.' },
  { name: 'Morehouse College', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Atlanta', state: 'GA', website: 'https://www.morehouse.edu', notes: 'Special collections and archives; MLK Jr. papers connection.' },
  { name: 'Morgan State University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Baltimore', state: 'MD', website: 'https://www.morgan.edu', notes: 'Earl S. Richardson Library; growing archives and digitization program.' },
  { name: 'Tuskegee University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Tuskegee', state: 'AL', website: 'https://www.tuskegee.edu', notes: 'National Historic Site on campus; Booker T. Washington and Tuskegee Airmen archives.' },
  { name: 'Clark Atlanta University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Atlanta', state: 'GA', website: 'https://www.cau.edu', notes: 'Robert W. Woodruff Library shared with Morehouse, Spelman, and Morehouse School of Medicine.' },
  { name: 'Xavier University of Louisiana', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'New Orleans', state: 'LA', website: 'https://www.xula.edu', notes: 'Archives include significant African American Catholic and New Orleans history collections.' },
  { name: 'Prairie View A&M University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Prairie View', state: 'TX', website: 'https://www.pvamu.edu', notes: 'Special collections and university archives; HBCU history preservation.' },
  { name: 'North Carolina A&T State University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Greensboro', state: 'NC', website: 'https://www.ncat.edu', notes: 'Special collections include civil rights sit-in documentation; Greensboro Four history.' },
  { name: 'Grambling State University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Grambling', state: 'LA', website: 'https://www.gram.edu', notes: 'HBCU archives and institutional history preservation.' },
  { name: 'Tennessee State University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Nashville', state: 'TN', website: 'https://www.tnstate.edu', notes: 'Special collections with significant African American history in Middle Tennessee.' },
  { name: 'Bowie State University', institution_type: 'HBCU / University', relationship_status: 'Target', city: 'Bowie', state: 'MD', website: 'https://www.bowiestate.edu', notes: 'Oldest HBCU in Maryland; archives and historic campus preservation.' },

  // ── Other Universities with Strong Preservation / Archives Programs
  { name: 'University of Maryland', institution_type: 'University', relationship_status: 'Target', city: 'College Park', state: 'MD', website: 'https://www.umd.edu', notes: 'iSchool (Library and Information Science) and African American collections.' },
  { name: 'American University', institution_type: 'University', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.american.edu', notes: 'Special collections and Washington DC regional history.' },
  { name: 'Georgetown University', institution_type: 'University', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://www.georgetown.edu', notes: 'GU272 descendants project; significant archival collections and historic campus.' },

  // ── Smithsonian Affiliates & Broader Network ──────────────────────
  { name: 'Smithsonian Affiliations Program', institution_type: 'Program', relationship_status: 'Target', city: 'Washington', state: 'DC', website: 'https://affiliations.si.edu', notes: '200+ affiliated museums across the US; good pipeline for outreach and partnership.' },
];

module.exports = { institutions };
