INSERT IGNORE INTO keywords (keyword, priority) VALUES
('digitization',                'High'),
('archival',                    'High'),
('archiving',                   'High'),
('archives',                    'High'),
('collection management',       'High'),
('heritage preservation',       'High'),
('preservation',                'High'),
('digital preservation',        'High'),
('scanning',                    'Medium'),
('metadata',                    'Medium'),
('finding aid',                 'Medium'),
('EAD',                         'Medium'),
('DACS',                        'Medium'),
('digitize',                    'High'),
('library services',            'Medium'),
('museum collections',          'High'),
('historical society',          'Medium'),
('HBCU',                        'High'),
('African American history',    'High'),
('Black history',               'High'),
('document management',         'Medium'),
('records management',          'Medium'),
('oral history',                'Medium'),
('special collections',         'Medium'),
('photograph digitization',     'High'),
('photographic services',       'Medium'),
('archival processing',         'High'),
('arrangement and description', 'Medium'),
('institutional archives',      'High');
