INSERT INTO keywords (keyword, active, track, priority, notes) VALUES
('digitization',               1, 'All',        'High',   NULL),
('archival',                   1, 'All',        'High',   NULL),
('archiving',                  1, 'All',        'High',   NULL),
('archives',                   1, 'All',        'High',   NULL),
('collection management',      1, 'All',        'High',   NULL),
('heritage preservation',      1, 'All',        'High',   NULL),
('preservation',               1, 'All',        'High',   NULL),
('digital preservation',       1, 'All',        'High',   NULL),
('scanning',                   1, 'All',        'Medium', NULL),
('metadata',                   1, 'All',        'Medium', NULL),
('finding aid',                1, 'All',        'Medium', NULL),
('EAD',                        1, 'Government', 'Medium', 'Encoded Archival Description'),
('DACS',                       1, 'All',        'Medium', 'Describing Archives Content Standard'),
('digitize',                   1, 'All',        'High',   NULL),
('library services',           1, 'All',        'Medium', NULL),
('museum collections',         1, 'Grant',      'High',   NULL),
('historical society',         1, 'Grant',      'Medium', NULL),
('HBCU',                       1, 'All',        'High',   'Historically Black Colleges and Universities'),
('African American history',   1, 'Grant',      'High',   NULL),
('Black history',              1, 'Grant',      'High',   NULL),
('document management',        1, 'Government', 'Medium', NULL),
('records management',         1, 'Government', 'Medium', NULL),
('oral history',               1, 'All',        'Medium', NULL),
('special collections',        1, 'All',        'Medium', NULL),
('photograph digitization',    1, 'All',        'High',   NULL),
('photographic services',      1, 'All',        'Medium', NULL),
('archival processing',        1, 'All',        'High',   NULL),
('arrangement and description',1, 'All',        'Medium', NULL),
('institutional archives',     1, 'All',        'High',   NULL);
