INSERT IGNORE INTO user_settings (name, value, setting_type, description) VALUES
('digest_email_address',          'info@legacypnp.ltd',        'Email',  'Address to send the daily digest to'),
('digest_delivery_time',          '07:00',                     'Text',   'Time to send digest (HH:MM, 24h, Pacific Time)'),
('minimum_contract_amount',       '5000',                      'Number', 'Filter out opportunities below this dollar amount'),
('minimum_alignment_score',       '4',                         'Number', 'Minimum score (1-10) to include in digest'),
('preferred_regions',             'California,Northeast,National', 'List', 'Comma-separated list of preferred regions'),
('timezone',                      'America/Los_Angeles',        'Text',   'System timezone for all dates and digest delivery'),
('backup_frequency',              'daily',                     'Text',   'How often to back up the database'),
('backup_destination',            '',                          'Text',   'Path or destination for automated backups'),
('sam_gov_naics_codes',           '519120,541990,561410,541922,518210,541511,541512,541611,541922,712110,561990,611420', 'List', 'NAICS codes to include in SAM.gov queries'),
('alignment_naics_weight',        '5',                         'Number', 'Points added to alignment score per NAICS match'),
('alignment_keyword_high_weight', '3',                         'Number', 'Points for a High priority keyword match'),
('alignment_keyword_med_weight',  '2',                         'Number', 'Points for a Medium priority keyword match'),
('alignment_keyword_low_weight',  '1',                         'Number', 'Points for a Low priority keyword match'),
('alignment_set_aside_weight',    '2',                         'Number', 'Points for WOSB/EDWOSB set-aside match'),
('alignment_region_weight',       '1',                         'Number', 'Points for preferred region match'),
('company_cage',                  '9XVN3',                     'Profile','CAGE code — used in bid prep'),
('company_uei',                   'W9MNGXEFKBS9',              'Profile','UEI — used in SAM.gov queries and bid prep'),
('company_certifications',        'WOSB, EDWOSB, MBE',         'Profile','Active certifications'),
('company_website',               '',                          'Profile','Company website — included in outreach email drafts'),
('company_business_name',         'Legacy Planning & Preservation Ltd.', 'Profile', 'Business name'),
('company_owner_name',            '',                          'Profile','Owner''s name'),
('company_years_in_business',     '',                          'Profile','Years in business'),
('company_logo_path',             '',                          'Internal','Company logo file path — set via upload, not directly editable'),
('sam_registration_renewal_date', '',                          'Text',   'SAM.gov registration expiration date (YYYY-MM-DD)');
